//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CopyNESW.rc
//
#define IDS_APP_TITLE                   1
#define IDI_COPYNESW                    100
#define IDI_SMALL                       101
#define IDD_MAINMENU                    102
#define IDD_SELECTPLUGIN                103
#define IDD_PLAYNSF                     104
#define IDD_GENERICPROMPT               105
#define IDD_OPTIONS                     106
#define IDD_GENERICPROMPTLONG           107
#define IDD_STATUS                      108
#define IDD_BANKWATCH                   109
#define IDR_DRIVER                      110
#define IDD_MICROBUG                    111
#define IDD_VRC7TUNER                   112
#define IDC_MAIN_MAKENES                1000
#define IDC_MAIN_MAKEUNIF               1001
#define IDC_MAIN_SPLITNES               1002
#define IDC_MAIN_SPLITUNIF              1003
#define IDC_MAIN_BREAKBANK              1004
#define IDC_MAIN_DISASM                 1005
#define IDC_MAIN_OPTIONS                1006
#define IDC_MAIN_NESINFO                1007
#define IDC_MAIN_PLAYCART               1008
#define IDC_MAIN_RAMCART                1009
#define IDC_MAIN_PLAYNSF                1010
#define IDC_MAIN_REGPLAY                1011
#define IDC_MAIN_DUMPCART               1012
#define IDC_MAIN_WRITEWRAM              1013
#define IDC_MAIN_RUNPLUG                1014
#define IDC_MAIN_FIXGAR                 1015
#define IDC_MAIN_BANKWATCH              1016
#define IDC_MAIN_MICROBUG               1017
#define IDC_MAIN_VRC7REGS               1018
#define IDC_PROMPT_TITLE                1019
#define IDC_PROMPT_DATA                 1020
#define IDC_PLUGIN_CATEGORY             1021
#define IDC_PLUGIN_LIST                 1022
#define IDC_PLUGIN_DESC                 1023
#define IDC_STATUS_TEXT                 1024
#define IDC_STATUS_BUTTON               1025
#define IDC_STATUS_GRAPH                1026
#define IDC_CONFIG_SAVECRC              1027
#define IDC_CONFIG_SAVEPARTS            1028
#define IDC_CONFIG_PRGDIR               1029
#define IDC_CONFIG_PRGBUTTON            1030
#define IDC_CONFIG_CHRDIR               1031
#define IDC_CONFIG_CHRBUTTON            1032
#define IDC_CONFIG_WRAMDIR              1033
#define IDC_CONFIG_WRAMBUTTON           1034
#define IDC_CONFIG_NESDIR               1035
#define IDC_CONFIG_NESBUTTON            1036
#define IDC_CONFIG_CRCDIR               1037
#define IDC_CONFIG_CRCBUTTON            1038
#define IDC_CONFIG_NSFDIR               1039
#define IDC_CONFIG_NSFBUTTON            1040
#define IDC_CONFIG_PLUGDIR              1041
#define IDC_CONFIG_PLUGBUTTON           1042
#define IDC_CONFIG_PORT                 1043
#define IDC_CONFIG_ADDR                 1044
#define IDC_NSF_TITLE                   1045
#define IDC_NSF_ARTIST                  1046
#define IDC_NSF_COPYRIGHT               1047
#define IDC_NSF_CURSONG                 1048
#define IDC_NSF_MAXSONGS                1049
#define IDC_NSF_PREVIOUS                1050
#define IDC_NSF_NEXT                    1051
#define IDC_NSF_REPLAY                  1052
#define IDC_BANK_HISTORY                1053
#define IDC_BANK_CLRHIST                1054
#define IDC_BANK_ADDR                   1055
#define IDC_BANK_DATA                   1056
#define IDC_BANK_READ                   1057
#define IDC_BANK_WRITE                  1058
#define IDC_BANK_RUN                    1059
#define IDC_BANK_RESET                  1060
#define IDC_BANK_NT0                    1061
#define IDC_BANK_NT1                    1062
#define IDC_BANK_NT2                    1063
#define IDC_BANK_NT3                    1064
#define IDC_BANK_UPDATE                 1065
#define IDC_BANK_RES                    1066
#define IDC_BANK_CRC                    1067
#define IDC_BANK_DUMP                   1068
#define IDC_BANK_DUMPFROM               1069
#define IDC_BANK_DUMPTO                 1070
#define IDC_BANK_RECV                   1071
#define IDC_BANK_LOAD                   1072
#define IDC_BANK_CLR                    1073
#define IDC_BANK_CUST1                  1074
#define IDC_BANK_CNT1                   1075
#define IDC_BANK_CUST2                  1076
#define IDC_BANK_CNT2                   1077
#define IDC_BANK_CUST3                  1078
#define IDC_BANK_CNT3                   1079
#define IDC_BANK_INFO                   1080
#define IDC_BANK_PROGRESS               1081
#define IDC_MICRO_DISPGUP               1082
#define IDC_MICRO_DISPC                 1083
#define IDC_MICRO_DISUP                 1084
#define IDC_MICRO_DISASM                1085
#define IDC_MICRO_DISPGDN               1086
#define IDC_MICRO_DISBP                 1087
#define IDC_MICRO_DISDN                 1088
#define IDC_MICRO_REGX                  1089
#define IDC_MICRO_REGY                  1090
#define IDC_MICRO_REGA                  1091
#define IDC_MICRO_REGSP                 1092
#define IDC_MICRO_REGPC                 1093
#define IDC_MICRO_REGFN                 1094
#define IDC_MICRO_REGFV                 1095
#define IDC_MICRO_REGFD                 1096
#define IDC_MICRO_REGFI                 1097
#define IDC_MICRO_REGFZ                 1098
#define IDC_MICRO_REGFC                 1099
#define IDC_MICRO_REGWATCH              1100
#define IDC_MICRO_REGCURSOR             1101
#define IDC_MICRO_REGBREAK              1102
#define IDC_MICRO_REGSCAN               1103
#define IDC_MICRO_REGMODE               1104
#define IDC_MICRO_REGBADOP              1105
#define IDC_MICRO_NMI                   1106
#define IDC_MICRO_RESET                 1107
#define IDC_MICRO_IRQ                   1108
#define IDC_MICRO_JMP                   1109
#define IDC_MICRO_BREAK                 1110
#define IDC_MICRO_STEP                  1111
#define IDC_MICRO_RUNTO                 1112
#define IDC_MICRO_WRITE                 1113
#define IDC_MICRO_BANKENAB              1114
#define IDC_MICRO_BANKCLR               1115
#define IDC_MICRO_BANKLIST              1116
#define IDC_MICRO_WATCHENAB             1117
#define IDC_MICRO_WATCHUP2              1118
#define IDC_MICRO_WATCHUP1              1119
#define IDC_MICRO_WATCHDN1              1120
#define IDC_MICRO_WATCHDN2              1121
#define IDC_MICRO_WATCHLIST             1122
#define IDC_VRC7_INSTSLID               1123
#define IDC_VRC7_INSTEDIT               1124
#define IDC_VRC7_OCTSLID                1125
#define IDC_VRC7_OCTEDIT                1126
#define IDC_VRC7_CUSTOM                 1127
#define IDC_VRC7_BUILTIN                1128
#define IDC_VRC7_PLAY                   1129
#define IDC_VRC7_STOP                   1130
#define IDC_VRC7_SAVE                   1131
#define IDC_VRC7_CTREMOLO               1132
#define IDC_VRC7_CVIBRATO               1133
#define IDC_VRC7_CSUSTAIN               1134
#define IDC_VRC7_CKSR                   1135
#define IDC_VRC7_CMULTSLID              1136
#define IDC_VRC7_CMULTEDIT              1137
#define IDC_VRC7_CKEYSLID               1138
#define IDC_VRC7_CKEYEDIT               1139
#define IDC_VRC7_CFEEDSLID              1140
#define IDC_VRC7_CFEEDEDIT              1141
#define IDC_VRC7_CFSINE                 1142
#define IDC_VRC7_CHSINE                 1143
#define IDC_VRC7_CASLID                 1144
#define IDC_VRC7_CAEDIT                 1145
#define IDC_VRC7_CDSLID                 1146
#define IDC_VRC7_CDEDIT                 1147
#define IDC_VRC7_CSSLID                 1148
#define IDC_VRC7_CSEDIT                 1149
#define IDC_VRC7_CRSLID                 1150
#define IDC_VRC7_CREDIT                 1151
#define IDC_VRC7_MTREMOLO               1152
#define IDC_VRC7_MVIBRATO               1153
#define IDC_VRC7_MSUSTAIN               1154
#define IDC_VRC7_MKSR                   1155
#define IDC_VRC7_MMULTSLID              1156
#define IDC_VRC7_MMULTEDIT              1157
#define IDC_VRC7_MKEYSLID               1158
#define IDC_VRC7_MKEYEDIT               1159
#define IDC_VRC7_MVOLSLID               1160
#define IDC_VRC7_MVOLEDIT               1161
#define IDC_VRC7_MFSINE                 1162
#define IDC_VRC7_MHSINE                 1163
#define IDC_VRC7_MASLID                 1164
#define IDC_VRC7_MAEDIT                 1165
#define IDC_VRC7_MDSLID                 1166
#define IDC_VRC7_MDEDIT                 1167
#define IDC_VRC7_MSSLID                 1168
#define IDC_VRC7_MSEDIT                 1169
#define IDC_VRC7_MRSLID                 1170
#define IDC_VRC7_MREDIT                 1171
#define IDC_MAIN_RECONNECT              1172
#define IDC_CONFIG_MAKEUNIF             1173
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        113
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
